### PR TITLE
Fix build for gcc-15/16

### PR DESCRIPTION
**Pull request by Pritchy96**
GCC-15/16 was still failing after #852, with a similar error to the one originally raised (#851):

```
make all
...
cc -O2 -Wall -Werror  -Isrc/ -Isrc/include -Iinclude/   -Isrc/ -Isrc/include -Iinclude/ -c src/anaarg.c -o obj/anaarg.o
src/anaarg.c: In function ‘analize_arguments’:
src/anaarg.c:131:60: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  131 |                                                         cp = strchr(opttable->option, ':');
      |                                                            ^
cc1: all warnings being treated as errors
```

This PR fixes that and GCC-15/16 now compiles cleanly.

### CODE REVIEW

**Comment by uyjulian** [comment]
Lgtm
